name: angular2_material
description: >
  DEPRECATED: Google's official AngularDart Material Design Components are now
  published as `angular_components`.
version: 2.0.0-beta.11
homepage: https://github.com/dart-lang/angular_components
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  browser: ^0.10.0
  angular2: 2.0.0-beta.10
dev_dependencies:
  guinness2: 0.0.4
transformers:
  - angular2/transform/codegen
